version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: llm-backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite:///local.db
    volumes:
      - ./model:/app/model
      - ./queries.db:/app/queries.db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: llm-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
